# Generated by Django 4.1.7 on 2023-03-23 02:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vitals", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vitals",
            options={"verbose_name_plural": "Vitals"},
        ),
    ]
